spring:
  application:
    name: Mikhaylov-Ivan-2-semester
  datasource:
    driver-class-name: org.postgresql.Driver
  cache:
    type: simple
  sql:
    init:
      mode: always

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
